# Generated by Django 5.0.1 on 2026-09-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizquestion_quizsettings_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='reading_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
