# Generated by Django 5.0.1 on 2026-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_plain_password_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='reading_pdf',
            field=models.FileField(blank=True, null=True, upload_to='unit_pdfs/', verbose_name='Reading PDF'),
        ),
    ]
